## -*-makefile-*-

## SKEL v$Revision: 1.1 $: Common rules to all the makefiles
## ----
## 
## $Id: Makefile.rules,v 1.1 2003/06/13 23:51:18 nguyhien Exp $
##
##  LONG DESCRIPTION HERE. EXPLAIN WHAT THIS FILE DOES OR IS USED
## FOR. DON'T BE AFRAID TO USE TOO MUCH WORDING. HOWEVER,
## SPECIFICATIONS SHOULD BE AT SKEL/doc.
##
##  Full changelog at file bottom.
##
## (C) YEAR by AUTHOR <EMAIL>
##      [: THINGS DONE BY AUTHOR]

## type: deep, strictness: gnu

# Generate pre-parsed CC code.
%.i: %.cc
	$(COMPILE) -E -c $^ -o $@

.PRECIOUS: %.ii
%.cci: %.ii
	-grep -v -e "^#" -e "^ *$$" $^ | indent > $@
	mv -f $@ $^


## FIXME: Your stuff here


## $Log: Makefile.rules,v $
## Revision 1.1  2003/06/13 23:51:18  nguyhien
## autoconf
##
## Revision 1.1.1.1  2002/09/18 17:24:54  yzou
## initial importing for evlog subagent.
##
## Revision 1.1  2002/03/08 19:48:11  yzou
## adding new files. changing some directory structure.
##
## Revision 1.1  2002/02/26 02:23:25  yzou
## converting the package to use automake.
##
## Revision 1.2  2001/11/10 02:48:03  inaky
## Removed old logs, now CVS keywords ain't expanded
##
