#define yy_create_buffer tt_create_buffer
#define yy_delete_buffer tt_delete_buffer
#define yy_scan_buffer tt_scan_buffer
#define yy_scan_string tt_scan_string
#define yy_scan_bytes tt_scan_bytes
#define yy_flex_debug tt_flex_debug
#define yy_init_buffer tt_init_buffer
#define yy_flush_buffer tt_flush_buffer
#define yy_load_buffer_state tt_load_buffer_state
#define yy_switch_to_buffer tt_switch_to_buffer
#define yyin ttin
#define yyleng ttleng
#define yylex ttlex
#define yyout ttout
#define yyrestart ttrestart
#define yytext tttext

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 59
#define YY_END_OF_BUFFER 60
static yyconst short int yy_accept[269] =
    {   0,
        0,    0,   60,   58,   53,   55,   48,   58,   58,   58,
       35,   36,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   54,   53,   58,    0,
        0,   46,   57,   45,   35,    0,    0,    0,   36,   33,
       49,    0,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
        0,    0,    0,   40,    0,    0,    0,    0,   45,    0,
        0,   47,   34,    0,    0,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   15,

       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,    0,   39,   37,    0,    0,
        0,   46,    0,   45,   44,    0,    0,    0,   33,   33,
       33,   13,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   16,   33,   33,   33,   33,   33,   33,
       33,   33,   27,   33,   33,   33,   33,   33,    0,   37,
       38,   43,   41,    0,    0,   33,   33,   33,    3,   33,
       33,   33,   33,   33,   33,   21,   33,   33,   33,   33,
       33,   24,   17,   33,   33,   33,   33,   26,   28,   33,
       33,   31,   33,   56,   41,   42,   33,   33,   33,   33,

       33,   33,   14,   33,   33,   33,    9,   33,   33,   33,
       18,   25,   11,   33,   33,   33,   30,   33,   20,    1,
       33,    4,   33,   33,   33,   33,    0,   50,    0,   22,
       33,   33,   12,   33,   33,   32,   33,   33,   33,   33,
        8,    0,    0,   23,   10,   33,   19,   33,    5,   33,
       33,    0,    0,   29,    2,   33,    7,    0,    0,    6,
        0,    0,    0,    0,   51,    0,   52,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    7,    1,
        1,    8,    9,    1,    9,   10,   11,   12,   13,   13,
       13,   13,   13,   13,   13,   14,   14,    1,    1,    1,
        1,    1,    1,    1,   15,   15,   15,   15,   16,   15,
       17,   17,   17,   17,   17,   18,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   19,   17,   17,
        1,   20,    1,    1,   21,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   17,   17,   31,   32,   33,
       34,   35,   17,   36,   37,   38,   39,   40,   41,   42,
       43,   17,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        1,    4,    4,    4,    4,    4,    5,    5,    5,    1,
        5,    4,    4,    4,    4,    4,    4,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1
    } ;

static yyconst short int yy_base[277] =
    {   0,
        0,   43,  391,  392,  392,  392,  392,  370,   34,  381,
       40,   48,    0,   50,   38,   36,   41,  348,   46,   39,
       53,  361,   55,  343,   59,   49,  392,   89,  383,  377,
       85,   87,  392,   92,  107,  112,   98,    0,  127,    0,
      392,  363,  357,  351,  342,  357,  345,  105,  338,  350,
      351,  340,  337,  337,  333,  336,  336,  343,  338,  332,
      337,  328,  328,  333,  328,  326,  322,  329,  328,  318,
      128,  353,  133,  392,  347,  102,  346,  142,  136,  151,
      145,  154,    0,   74,  157,  316,  323,  314,  313,  311,
      325,  316,  321,  321,  310,  312,  319,  308,  305,    0,

      299,  309,  306,  313,  298,  300,  141,  306,  309,  292,
      296,  298,  293,  304,  289,  170,  392,  392,  166,  317,
      162,  173,  176,  179,  392,  316,  188,  315,  295,  287,
      289,    0,  280,  278,  284,  279,  283,  275,  281,  273,
      288,  273,  285,  276,  270,  269,  266,  277,  269,  277,
      275,  263,    0,  270,  269,  260,  259,  264,  192,  392,
      392,  392,  392,  191,  286,  255,  265,  267,    0,  258,
      258,  257,  260,  264,  254,    0,  245,  244,  250,  246,
      253,    0,    0,  253,  249,  238,  249,    0,  243,  235,
      224,    0,  223,  392,  392,  392,  213,  221,  206,  206,

      204,  206,    0,  202,  201,  203,    0,  212,  204,  212,
        0,    0,    0,  208,  200,  207,    0,  204,    0,    0,
      193,    0,  204,  191,  185,  184,  206,  392,  209,    0,
      198,  187,    0,  191,  198,    0,  196,  185,  190,  184,
        0,  180,  180,    0,    0,  188,    0,  178,    0,  180,
      176,  160,  143,    0,    0,  144,    0,  131,  108,    0,
       98,   99,   88,   69,  392,   60,  392,  392,  247,  249,
      254,   47,  259,  262,  266,  269
    } ;

static yyconst short int yy_def[277] =
    {   0,
      268,    1,  268,  268,  268,  268,  268,  269,  268,  268,
      268,  268,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  268,  268,  268,  268,
      271,  268,  268,  268,  268,  268,  268,  272,  268,  270,
      268,  273,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      268,  268,  268,  268,  268,  268,  274,  268,  268,  268,
      268,  268,  272,  273,  275,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  268,  268,  268,  268,  274,
      268,  268,  268,  268,  268,  268,  268,  276,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  268,  268,
      268,  268,  268,  268,  276,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  268,  268,  268,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  268,  268,  268,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  268,  268,  270,  270,  270,  270,  270,  270,  270,
      270,  268,  268,  270,  270,  270,  270,  268,  268,  270,
      268,  268,  268,  268,  268,  268,  268,    0,  268,  268,
      268,  268,  268,  268,  268,  268
    } ;

static yyconst short int yy_nxt[437] =
    {   0,
        4,    5,    6,    5,    7,    4,    8,    4,    4,    9,
       10,   11,   12,   12,   13,   13,   13,   14,   13,    4,
       13,   15,   13,   16,   17,   18,   19,   13,   13,   20,
       21,   13,   13,   13,   13,   22,   23,   24,   25,   13,
       26,   13,   13,   27,   28,   32,   32,   32,   29,   34,
       83,   35,   35,   36,   41,   37,   42,   34,   38,   39,
       39,   39,   43,   37,   46,   37,   48,   51,   44,   47,
       54,   55,   69,   37,   49,   45,   52,   56,   59,   53,
      125,   38,   64,   60,   61,   70,   57,  267,   65,   66,
       71,   67,   62,  268,   72,   68,   76,   76,   32,   32,

       32,  266,   78,   79,   79,   79,   81,   80,  118,   82,
       82,   82,   78,  119,  119,  265,   34,   80,   35,   35,
       36,   34,   37,   36,   36,   36,   77,   37,  264,   71,
      263,   91,   37,   72,   73,   92,   34,   37,   39,   39,
       39,   93,   37,  262,  116,  116,  116,   79,   79,   79,
      121,   80,   37,  122,  122,  122,   82,   82,   82,  123,
      261,   80,  124,  124,  124,   82,   82,   82,  127,  127,
      149,  159,  160,  122,  122,  122,  260,  119,  119,  150,
      259,  116,  116,  116,  122,  122,  122,  124,  124,  124,
      124,  124,  124,  159,  163,  258,  194,  195,  128,  164,

      164,  257,  164,  164,  227,  228,  229,  227,  228,  229,
      229,  228,  229,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  226,  225,
      224,  223,  242,  222,  221,  220,  243,   30,   30,  219,
       30,   30,   40,   40,   75,  218,   75,   75,   75,   84,
       84,  217,   84,   84,  120,  120,  126,  216,  126,  126,
      126,  165,  165,  215,  214,  213,  212,  211,  210,  209,
      208,  207,  206,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  193,  192,  191,  190,  189,  188,  187,

      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  162,  162,  161,  158,  157,  156,  155,  154,  153,
      152,  151,  148,  147,  146,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  136,  135,  134,  133,  132,  131,
      130,  129,  117,  117,   73,  115,  114,  113,  112,  111,
      110,  109,  108,  107,  106,  105,  104,  103,  102,  101,
      100,   99,   98,   97,   96,   95,   94,   90,   89,   88,
       87,   86,   85,   74,   73,   63,   58,   50,   33,   31,
      268,    3,  268,  268,  268,  268,  268,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268
    } ;

static yyconst short int yy_chk[437] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    9,    9,    9,    2,   11,
      272,   11,   11,   11,   14,   11,   14,   12,   11,   12,
       12,   12,   15,   12,   16,   11,   17,   19,   15,   16,
       20,   20,   26,   12,   17,   15,   19,   21,   23,   19,
       84,   11,   25,   23,   23,   26,   21,  266,   25,   25,
       28,   25,   23,   84,   28,   25,   31,   31,   32,   32,

       32,  264,   32,   34,   34,   34,   37,   34,   76,   37,
       37,   37,   32,   76,   76,  263,   35,   34,   35,   35,
       35,   36,   35,   36,   36,   36,   31,   36,  262,   71,
      261,   48,   35,   71,   73,   48,   39,   36,   39,   39,
       39,   48,   39,  259,   73,   73,   73,   79,   79,   79,
       78,   79,   39,   78,   78,   78,   81,   81,   81,   80,
      258,   79,   80,   80,   80,   82,   82,   82,   85,   85,
      107,  116,  119,  121,  121,  121,  256,  119,  119,  107,
      253,  116,  116,  116,  122,  122,  122,  123,  123,  123,
      124,  124,  124,  159,  127,  252,  159,  164,   85,  127,

      127,  251,  164,  164,  206,  206,  206,  227,  227,  227,
      229,  229,  229,  250,  248,  246,  243,  242,  240,  239,
      238,  237,  235,  234,  232,  231,  226,  225,  224,  223,
      221,  218,  216,  215,  214,  210,  209,  208,  205,  204,
      202,  201,  227,  200,  199,  198,  227,  269,  269,  197,
      269,  269,  270,  270,  271,  193,  271,  271,  271,  273,
      273,  191,  273,  273,  274,  274,  275,  190,  275,  275,
      275,  276,  276,  189,  187,  186,  185,  184,  181,  180,
      179,  178,  177,  175,  174,  173,  172,  171,  170,  168,
      167,  166,  165,  158,  157,  156,  155,  154,  152,  151,

      150,  149,  148,  147,  146,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  136,  135,  134,  133,  131,  130,
      129,  128,  126,  120,  115,  114,  113,  112,  111,  110,
      109,  108,  106,  105,  104,  103,  102,  101,   99,   98,
       97,   96,   95,   94,   93,   92,   91,   90,   89,   88,
       87,   86,   77,   75,   72,   70,   69,   68,   67,   66,
       65,   64,   63,   62,   61,   60,   59,   58,   57,   56,
       55,   54,   53,   52,   51,   50,   49,   47,   46,   45,
       44,   43,   42,   30,   29,   24,   22,   18,   10,    8,
        3,  268,  268,  268,  268,  268,  268,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../../../user/lib/template/tmpllex.l"
#define INITIAL 0
#line 2 "../../../user/lib/template/tmpllex.l"
/*
 * Linux Event Logging for the Enterprise
 * Copyright (C) International Business Machines Corp., 2001
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 *  Please send e-mail to lkessler@users.sourceforge.net if you have
 *  questions or comments.
 *
 *  Project Website:  http://evlog.sourceforge.net/
 */
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <wchar.h>
#include <assert.h>

#include "evl_template.h"
#include "tt.tab.h"

/*
 * Internationalization support: flex should work OK with input files encoded
 * in character encodings such as ASCII, Latin-1, and UTF-8.  For these
 * character sets, a null byte appears only at the end of a string.
 * For encodings such as UCS-2 and UCS-4, the text may be full of null bytes,
 * so we can't handle those.
 */

#define MYEOF '\0'

static int getOctalEscape(const char *digits, int isCharConst);
static wchar_t getHexEscape(const char *digits);
static int getCharEscape(char c);
static char *getString(int quoted);
static int skipComment();
static void processLineDirective();

static int inputFromFile = 1;
static tmpl_parser_context_t *pc;
/* Define components of floating-point constants. */
#line 623 "lex.tt.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 62 "../../../user/lib/template/tmpllex.l"

#line 779 "lex.tt.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 269 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 392 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "../../../user/lib/template/tmpllex.l"
{ return TK_ALIGNED; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "../../../user/lib/template/tmpllex.l"
{ return TK_ATTRIBUTES; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "../../../user/lib/template/tmpllex.l"
{ return TK_CONST; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "../../../user/lib/template/tmpllex.l"
{ return TK_DEFAULT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "../../../user/lib/template/tmpllex.l"
{ return TK_DELIMITER; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "../../../user/lib/template/tmpllex.l"
{ return TK_DESCRIPTION; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "../../../user/lib/template/tmpllex.l"
{ return TK_EVENT_TYPE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "../../../user/lib/template/tmpllex.l"
{ return TK_FACILITY; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "../../../user/lib/template/tmpllex.l"
{ return TK_IMPORT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "../../../user/lib/template/tmpllex.l"
{ return TK_REDIRECT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "../../../user/lib/template/tmpllex.l"
{ return TK_STRUCT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "../../../user/lib/template/tmpllex.l"
{ return TK_TYPEDEF; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 76 "../../../user/lib/template/tmpllex.l"
{ return TK_TYCHAR; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 77 "../../../user/lib/template/tmpllex.l"
{ return TK_TYDOUBLE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 78 "../../../user/lib/template/tmpllex.l"
{ return TK_TYINT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 79 "../../../user/lib/template/tmpllex.l"
{ return TK_TYLONG; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 80 "../../../user/lib/template/tmpllex.l"
{ return TK_TYSHORT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 81 "../../../user/lib/template/tmpllex.l"
{ return TK_TYSIGNED; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 82 "../../../user/lib/template/tmpllex.l"
{ return TK_TYUNSIGNED; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 84 "../../../user/lib/template/tmpllex.l"
{ ttlval.ival = TY_ADDRESS;	return TK_TYPENAME; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 85 "../../../user/lib/template/tmpllex.l"
{ ttlval.ival = TY_FLOAT;	return TK_TYPENAME; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 86 "../../../user/lib/template/tmpllex.l"
{ ttlval.ival = TY_LDOUBLE;	return TK_TYPENAME; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 87 "../../../user/lib/template/tmpllex.l"
{ ttlval.ival = TY_LONGLONG;	return TK_TYPENAME; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 88 "../../../user/lib/template/tmpllex.l"
{ ttlval.ival = TY_CHAR;	return TK_TYPENAME; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 89 "../../../user/lib/template/tmpllex.l"
{ ttlval.ival = TY_STRING;	return TK_TYPENAME; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 90 "../../../user/lib/template/tmpllex.l"
{ ttlval.ival = TY_UCHAR;	return TK_TYPENAME; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 91 "../../../user/lib/template/tmpllex.l"
{ ttlval.ival = TY_UINT;	return TK_TYPENAME; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 92 "../../../user/lib/template/tmpllex.l"
{ ttlval.ival = TY_ULONG;	return TK_TYPENAME; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 93 "../../../user/lib/template/tmpllex.l"
{ ttlval.ival = TY_ULONGLONG;	return TK_TYPENAME; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 94 "../../../user/lib/template/tmpllex.l"
{ ttlval.ival = TY_USHORT;	return TK_TYPENAME; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 95 "../../../user/lib/template/tmpllex.l"
{ ttlval.ival = TY_WCHAR;	return TK_TYPENAME; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 96 "../../../user/lib/template/tmpllex.l"
{ ttlval.ival = TY_WSTRING;	return TK_TYPENAME; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 98 "../../../user/lib/template/tmpllex.l"
{
	char *thisName;
	if (! (thisName = strdup((const char*)yytext)) ) {
		perror("strdup");
		return(ERRTOK);
	}
	ttlval.sval = thisName;
	return TK_NAME;
	}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 108 "../../../user/lib/template/tmpllex.l"
{
	/* hex */
	ttlval.ival = strtoul((char *)yytext, (char **)NULL, 16);
	return TK_INTEGER;
	}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 113 "../../../user/lib/template/tmpllex.l"
{
	/* octal */
	ttlval.ival = strtoul((char *)yytext, (char **)NULL, 8);
	return TK_INTEGER;
	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 118 "../../../user/lib/template/tmpllex.l"
{
	/* decimal */
	ttlval.ival = strtoul((char *)yytext, (char **)NULL, 10);
	return TK_INTEGER;
	}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 124 "../../../user/lib/template/tmpllex.l"
{
	int c = getOctalEscape((char *)&yytext[2], 1);
	if (c > UCHAR_MAX) {
		return ERRTOK;
	}
	ttlval.cval = c;
	return TK_CHAR;
	}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 133 "../../../user/lib/template/tmpllex.l"
{
	ttlval.cval = (char) getHexEscape((char *)&yytext[3]);
	return TK_CHAR;
	}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 138 "../../../user/lib/template/tmpllex.l"
{
	ttlval.cval = getCharEscape((char)yytext[2]);
	return TK_CHAR;
	}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 143 "../../../user/lib/template/tmpllex.l"
{
	ttlval.cval = (char) yytext[1];
	return TK_CHAR;
	}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 148 "../../../user/lib/template/tmpllex.l"
{
	wchar_t c = getOctalEscape((char *)&yytext[3], 1);
	ttlval.wcval = c;
	return TK_WCHAR;
	}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 154 "../../../user/lib/template/tmpllex.l"
{
	ttlval.wcval = getHexEscape((char *)&yytext[4]);
	return TK_WCHAR;
	}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 159 "../../../user/lib/template/tmpllex.l"
{
	ttlval.wcval = getCharEscape((char)yytext[3]);
	return TK_WCHAR;
	}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 164 "../../../user/lib/template/tmpllex.l"
{
	wchar_t wc;
	int bytesToEat, bytesEaten;
	bytesToEat = strlen((char*)yytext) - 3;
	bytesEaten = mbtowc(&wc, yytext+2, bytesToEat);
	if (bytesEaten != bytesToEat) {
		return ERRTOK;
	}
	ttlval.wcval = wc;
	return TK_WCHAR;
	}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 176 "../../../user/lib/template/tmpllex.l"
{
	/* 1. or 1.1 or 1.exp or 1.1exp */
	ttlval.dval = atof((char *)yytext);
	return TK_DOUBLE;
	}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 182 "../../../user/lib/template/tmpllex.l"
{
	/* .1 or .1exp */
	ttlval.dval = atof((char *)yytext);
	return TK_DOUBLE;
	}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 188 "../../../user/lib/template/tmpllex.l"
{
	/* 1exp */
	ttlval.dval = atof((char *)yytext);
	return TK_DOUBLE;
	}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 194 "../../../user/lib/template/tmpllex.l"
{
	char *s = getString(1);
	if (!s) {
		return ERRTOK;
	}
	ttlval.sval = s;
	return TK_STRING;
	}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 203 "../../../user/lib/template/tmpllex.l"
{
	size_t nwc, nwc2;
	wchar_t *ws;
	char *s = getString(1);
	if (!s) {
		return ERRTOK;
	}
	/*
	 * At this point, s points to a null-terminated string of bytes,
	 * which may include multibyte characters.  (In particular, each \x
	 * escape has been converted to the appropriate multibyte sequence
	 * in s.)  Convert s to an array of wide characters in ws.
	 */
	nwc = mbstowcs(NULL, s, 0);	/* Count multibyte chars */
	if (nwc == (size_t)(-1)) {
		free(s);
		return ERRTOK;
	}
	ws = (wchar_t*) malloc((nwc+1) * sizeof(wchar_t));
	assert(ws != NULL);
	nwc2 = mbstowcs(ws, s, nwc+1);
	assert(nwc2 == nwc);
	free(s);
	ttlval.wsval = ws;
	return TK_WSTRING;
	}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 230 "../../../user/lib/template/tmpllex.l"
{
	/* Format specification at end of template */
	char *s;
	pc->pc_lineno++;	/* since we've eaten the \n after "format" */
	s = getString(0);
	if (!s) {
		return ERRTOK;
	}
	ttlval.sval = s;
	return TK_FORMAT;
	}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 242 "../../../user/lib/template/tmpllex.l"
{ return TK_FORMAT_STRING; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 244 "../../../user/lib/template/tmpllex.l"
{ return TK_FORMAT_WSTRING; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 246 "../../../user/lib/template/tmpllex.l"
;	/* Skip white space. */
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 248 "../../../user/lib/template/tmpllex.l"
;	/* Skip the terminating null, if it was not eaten with the TK_FORMAT string. */
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 250 "../../../user/lib/template/tmpllex.l"
{ pc->pc_lineno++; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 252 "../../../user/lib/template/tmpllex.l"
{
	processLineDirective();
	}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 256 "../../../user/lib/template/tmpllex.l"
{
	if (skipComment() < 0) {
		return ERRTOK;
	}
	}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 262 "../../../user/lib/template/tmpllex.l"
{
	/* Pass through any other characters. */
	return yytext[0];
	}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 266 "../../../user/lib/template/tmpllex.l"
ECHO;
	YY_BREAK
#line 1277 "lex.tt.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 44);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 269 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 44;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 269 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 268);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 266 "../../../user/lib/template/tmpllex.l"


static YY_BUFFER_STATE bufState;

void
_evlTmplReinitLex(const char *parseMe)
{
	/* Include a null character at the end. */
	bufState = yy_scan_bytes(parseMe, strlen(parseMe)+1);
	inputFromFile = 0;
	pc = _evlTmplGetParserContext();
}

void
_evlTmplEndLex()
{
	yy_delete_buffer(bufState);
}

/*
 * Collect the 1-to-3-digit octal number following a \.
 * If isCharConst is true, we're accumulating a char constant, so we flag
 * an error if there are excess digits.
 * Returns value > UCHAR_MAX if there's an error.
 */
static int
getOctalEscape(const char *digits, int isCharConst)
{
	int n = 0;
	int nDigits = 0;
	const char *c;
	for (c = digits; '0' <= *c && *c <= '7'; c++) {
		n *= 8;
		n += *c - '0';
		if (++nDigits == 3 && !isCharConst) {
			return n;
		} else if (nDigits > 3 && isCharConst) {
			return UCHAR_MAX+1;
		}
	}
	return n;
}

static wchar_t
getHexEscape(const char *digits)
{
	int n = 0;
	const char *c;
	for (c = digits; isxdigit(*c); c++) {
		n *= 16;
		if (isdigit(*c)) {
			n += *c - '0';
		} else {
			n += (10 + tolower(*c) - 'a');
		}
	}
	return n;
}

static int
getCharEscape(char c)
{
	switch (c) {
	case '\'':	return '\'';
	case '\"':	return '\"';
	case '\?':	return '\?';
	case '\\':	return '\\';
	case 'a':	return '\a';
	case 'b':	return '\b';
	case 'f':	return '\f';
	case 'n':	return '\n';
	case 'r':	return '\r';
	case 't':	return '\t';
	case 'v':	return '\v';
	case '\n':	return -1;
	default:	return c;
	}
}

static void
collectOctalDigits(char *digits, char firstDigit)
{
	int nDigits = 1;
	int c;
	digits[0] = firstDigit;

	while (nDigits <= 3) {
		c = input();
		if ('0' <= c && c <= '7') {
			digits[nDigits++] = c;
		} else {
			unput(c);
			break;
		}
	}
	digits[nDigits] = '\0';
}

static int
collectHexDigits(char *digits, int maxDigits)
{
	int nDigits = 0;
	int c;

	while (nDigits <= maxDigits) {
		c = input();
		if (isxdigit(c)) {
			digits[nDigits++] = c;
		} else {
			unput(c);
			break;
		}
	}
	digits[nDigits] = '\0';
	return nDigits;
}

/*
 * We have eaten the leading " in a quoted string.  Collect the characters
 * of the string into strbuf, and then return a strdup-ed copy of the string.
 * We end after eating the terminating ".
 */
static char *
getString(int quoted) {
	int nc = 0;
	int c;
#define MAXSTRLEN (10*1024)
#define STRSLOP 10	/* e.g., to handle a multibyte character at the end */
	char strbuf[MAXSTRLEN+STRSLOP];
	int endOfString = (quoted ? '\"' : MYEOF);

	for (;;) {
		c = input();
		if (c == endOfString) {
			break;
		} else if (c == MYEOF) {
			/* EOF in middle of quoted string. */
			return 0;
		} else if (c == '\\') {
			/* Collect and decode the escape sequence. */
			c = input();
			if (c == MYEOF) {
				/* End of input */
				if (quoted) {
					return 0;
				} else {
					/* Allow \ as the last character. */
					strbuf[nc++] = '\\';
					break;
				}
			} else if ('0' <= c && c <= '7') {
				char digits[3+1];
				collectOctalDigits(digits, c);
				strbuf[nc++] = getOctalEscape(digits, 0);
			} else if (c == 'x') {
				char digits[8+1];
				wchar_t wc;
				int nBytes;
				int nDigits = collectHexDigits(digits, 8);
				if (nDigits == 0) {
					/* \x, no digits: undefined in ANSI C */
					strbuf[nc++] = 'x';
				} else {
					wc = getHexEscape(digits);
					nBytes = wctomb(&strbuf[nc], wc);
					if (nBytes >= 1) {
						nc += nBytes;
					} else {
						/* Probably no locale set. */
						strbuf[nc++] = (char) wc;
					}
				}
			} else {
				int ce = getCharEscape(c);
				/* Elide escaped newlines (ce == -1). */
				if (ce == -1) {
					pc->pc_lineno++;
				} else {
					strbuf[nc++] = ce;
				}
			}
		} else {
			if (c == '\n') {
				pc->pc_lineno++;
			}
			strbuf[nc++] = c;
		}

		if (nc > MAXSTRLEN) {
			return 0;
		}
	}

	strbuf[nc] = '\0';
	return strdup(strbuf);
}

/*
 * We have already eaten the leading / and *.  Skip past the trailing * and /.
 */
static int
skipComment()
{
	int c;
	while ((c = input()) != MYEOF) {
		if (c == '\n') {
			pc->pc_lineno++;
		}

		/* Correctly handle multiple *s followed by /. */
		while (c == '*') {
			c = input();
			if (c == '/') {
				/* End of comment */
				return 0;
			} else if (c == MYEOF) {
				/* EOF after a '*'. */
				return -1;
			} else if (c == '\n') {
				pc->pc_lineno++;
			}
		}
	}

	/* End of file */
	return -1;
}

/*
 * This function processes the '# nnn "filename"' directive.  yytext contains
 * '# nnn "', where nnn is a sequence of digits.  Eat the rest
 * of the string and the newline that follows it, and set the line number and
 * pathname in the parser context accordingly.
 */
static void
processLineDirective()
{
	char *s = (char*) yytext;
	int lineno;
	char *path;
	int c;

	while (!isdigit(*s)) {
		s++;
	}
	lineno = (int) strtoul(s, NULL, 0);
	path = getString(1);
	if (!path) {
		return;
	}
	if (pc->pc_pathname == NULL || strcmp(path, pc->pc_pathname) != 0) {
		free((char*)pc->pc_pathname);
		pc->pc_pathname = path;
	}
	pc->pc_lineno = lineno;

	/*
	 * Eat the trailing newline and any extraneous characters preceding it.
	 * For example, in response to #include directives, cpp can generate
	 * directives like
	 *	# 28 "foo.h" 2 3
	 * We just ignore the " 2 3".
	 */
	do {
		c = input();
	} while (c != '\n' && c != MYEOF);
}
