#!/bin/sh

ela_name=$1
EVLNOTIFY=/sbin/evlnotify
if [ -z "$ela_name" ]; then
	echo "Usage:"
	echo "    ela_show <rule_name>"
	exit 1
fi

uid=`id -u`
if [ $uid != "0" ]; then
	echo "ERROR: Only root is allowed to use the ela tools"
	exit 1
fi

$EVLNOTIFY -s ${ela_name}

